version: '3.8'
services:
   web:
      build: .
      command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata seed.json && python manage.py runserver 0.0.0.0:8000"
      volumes:
      - .:/app
      ports:
          - 8000:8000