# Generated by Django 3.2.10 on 2024-05-10 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recreacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kid',
            options={'ordering': ['nome']},
        ),
        migrations.AlterUniqueTogether(
            name='kid',
            unique_together={('nome', 'numeroApartamento')},
        ),
    ]
